/*

undef defines, protects from pollution

*/
#undef TEMPLATE_CLASS_NAME
#undef TEMPLATE_NAMESPACE
#undef TEMPLATE_CLASS_PARAMETERS
#undef TEMPLATE_CLASS_ARRAYS
#undef TEMPLATE_CLASS_ARRAYS2
#undef TEMPLATE_CLASS_METHODS

#undef REFACTOR_GNC_STORAGE_IN_PARS // ongoing refactor

#undef TEMPLATE_CLASS_PARAMETERS_1
#undef TEMPLATE_CLASS_PARAMETERS_2
#undef TEMPLATE_CLASS_PARAMETERS_3
#undef TEMPLATE_CLASS_PARAMETERS_4

#undef TEMPLATE_CLASS_PARAMETERS_STRUCT
#undef TEMPLATE_CLASS_PARAMETERS_STRUCT_1
#undef TEMPLATE_CLASS_PARAMETERS_STRUCT_2
#undef TEMPLATE_CLASS_PARAMETERS_STRUCT_3
#undef TEMPLATE_CLASS_PARAMETERS_STRUCT_4
