[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "cuda_hello"
version = "0.1.0"
description = "CUDA + nanobind hello world"
authors = [{ name = "Richard" }]
requires-python = ">=3.8"

[tool.autopep8]
max_line_length = 1000