import enum
import nanobind
from _typeshed import Incomplete
from typing import Callable, ClassVar

blur: nanobind.nb_func
cuda_hello: nanobind.nb_func
generate_ao_map: nanobind.nb_func
generate_normal_map: nanobind.nb_func
print_debug_info: nanobind.nb_func

class Erosion2:
    _block: Incomplete
    block_size: Incomplete
    deposition_rate: Incomplete
    erosion_rate: Incomplete
    evaporation_rate: Incomplete
    flow_factor: Incomplete
    height: Incomplete
    height_map: Incomplete
    jitter: Incomplete
    max_height: Incomplete
    min_height: Incomplete
    mode: Incomplete
    rain_rate: Incomplete
    sediment_map: Incomplete
    slope_threshold: Incomplete
    steps: Incomplete
    width: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Erosion3:
    _block: Incomplete
    capacity: Incomplete
    debug_hash_cell_order: Incomplete
    deposit: Incomplete
    dh_out: Incomplete
    ds_out: Incomplete
    dw_out: Incomplete
    erode: Incomplete
    evaporation_rate: Incomplete
    height: Incomplete
    height_map: Incomplete
    max_water_outflow: Incomplete
    rain_rate: Incomplete
    sediment_map: Incomplete
    steps: Incomplete
    water_map: Incomplete
    width: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Erosion4:
    _block: Incomplete
    deposition_rate: Incomplete
    erosion_rate: Incomplete
    height: Incomplete
    height_map: Incomplete
    jitter: Incomplete
    mode: Incomplete
    sediment_map: Incomplete
    slope_threshold: Incomplete
    steps: Incomplete
    width: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class FluidSimulation:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        APPLE: ClassVar[FluidSimulation.Type] = ...
        ORANGE: ClassVar[FluidSimulation.Type] = ...
        POTATO: ClassVar[FluidSimulation.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    APPLE: ClassVar[FluidSimulation.Type] = ...
    ORANGE: ClassVar[FluidSimulation.Type] = ...
    POTATO: ClassVar[FluidSimulation.Type] = ...
    _block: Incomplete
    cell_size: Incomplete
    dt: Incomplete
    gravity: Incomplete
    height: Incomplete
    height_map: Incomplete
    height_map_out: Incomplete
    steps: Incomplete
    velocity_map: Incomplete
    velocity_map_out: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Noise:
    _block: Incomplete
    angle: Incomplete
    height: Incomplete
    image: Incomplete
    period: Incomplete
    period_x: Incomplete
    period_y: Incomplete
    period_z: Incomplete
    seed: Incomplete
    type: Incomplete
    warp_amp: Incomplete
    warp_scale: Incomplete
    width: Incomplete
    x: Incomplete
    y: Incomplete
    z: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class NoiseGenerator:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        Gradient2D: ClassVar[NoiseGenerator.Type] = ...
        Gradient3D: ClassVar[NoiseGenerator.Type] = ...
        Hash2D: ClassVar[NoiseGenerator.Type] = ...
        Hash3D: ClassVar[NoiseGenerator.Type] = ...
        Value2D: ClassVar[NoiseGenerator.Type] = ...
        Value3D: ClassVar[NoiseGenerator.Type] = ...
        WarpedValue2D: ClassVar[NoiseGenerator.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    Gradient2D: ClassVar[NoiseGenerator.Type] = ...
    Gradient3D: ClassVar[NoiseGenerator.Type] = ...
    Hash2D: ClassVar[NoiseGenerator.Type] = ...
    Hash3D: ClassVar[NoiseGenerator.Type] = ...
    Value2D: ClassVar[NoiseGenerator.Type] = ...
    Value3D: ClassVar[NoiseGenerator.Type] = ...
    WarpedValue2D: ClassVar[NoiseGenerator.Type] = ...
    angle: Incomplete
    period: Incomplete
    scale: Incomplete
    seed: Incomplete
    type: Incomplete
    warp_amp: Incomplete
    warp_scale: Incomplete
    x: Incomplete
    y: Incomplete
    z: Incomplete
    def __init__(self) -> None: ...
    def fill(self, *args, **kwargs): ...
    def generate(self, *args, **kwargs): ...

class Resample:
    _block: Incomplete
    angle: Incomplete
    function_mode: Incomplete
    input: Incomplete
    map_x: Incomplete
    map_y: Incomplete
    offset_x: Incomplete
    offset_y: Incomplete
    output: Incomplete
    relative_offset: Incomplete
    sample_mode: Incomplete
    scale_by_output_size: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class TemplateClass3:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        APPLE: ClassVar[TemplateClass3.Type] = ...
        ORANGE: ClassVar[TemplateClass3.Type] = ...
        POTATO: ClassVar[TemplateClass3.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    APPLE: ClassVar[TemplateClass3.Type] = ...
    ORANGE: ClassVar[TemplateClass3.Type] = ...
    POTATO: ClassVar[TemplateClass3.Type] = ...
    _block: Incomplete
    height: Incomplete
    image: Incomplete
    test: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self, *args, **kwargs): ...

class XTemplateTest:
    _block: Incomplete
    height: Incomplete
    image: Incomplete
    test: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...
