import enum
import nanobind
from _typeshed import Incomplete
from typing import Callable, ClassVar

blur: nanobind.nb_func
cuda_hello: nanobind.nb_func
generate_ao_map: nanobind.nb_func
generate_normal_map: nanobind.nb_func
print_debug_info: nanobind.nb_func
test: nanobind.nb_func
test123: nanobind.nb_func

class Erosion4:
    _block: Incomplete
    _height: Incomplete
    _width: Incomplete
    deposition_rate: Incomplete
    erosion_rate: Incomplete
    height_map: Incomplete
    jitter: Incomplete
    mode: Incomplete
    sediment_map: Incomplete
    slope_threshold: Incomplete
    steps: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Erosion5:
    _block: Incomplete
    _height: Incomplete
    _width: Incomplete
    correct_diagonal_distance: Incomplete
    debug: Incomplete
    debug_mod: Incomplete
    deposition_mode: Incomplete
    deposition_rate: Incomplete
    diffusion_rate: Incomplete
    erosion_mode: Incomplete
    erosion_rate: Incomplete
    evaporation_rate: Incomplete
    hardness_map: Incomplete
    height_map: Incomplete
    max_height: Incomplete
    max_water_outflow: Incomplete
    min_height: Incomplete
    outflow_carve: Incomplete
    rain_map: Incomplete
    rain_rate: Incomplete
    sediment_capacity: Incomplete
    sediment_map: Incomplete
    simple_erosion_rate: Incomplete
    slope_exponent: Incomplete
    slope_jitter: Incomplete
    slope_threshold: Incomplete
    steps: Incomplete
    water_map: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Erosion6:
    _block: Incomplete
    _height: Incomplete
    _width: Incomplete
    correct_diagonal_distance: Incomplete
    debug: Incomplete
    debug_mod: Incomplete
    deposition_mode: Incomplete
    deposition_rate: Incomplete
    diffusion_rate: Incomplete
    erosion_mode: Incomplete
    erosion_rate: Incomplete
    evaporation_rate: Incomplete
    hardness_map: Incomplete
    height_map: Incomplete
    max_height: Incomplete
    max_water_outflow: Incomplete
    min_height: Incomplete
    outflow_carve: Incomplete
    rain_map: Incomplete
    rain_rate: Incomplete
    sediment_capacity: Incomplete
    sediment_map: Incomplete
    simple_erosion_rate: Incomplete
    slope_exponent: Incomplete
    slope_jitter: Incomplete
    slope_threshold: Incomplete
    steps: Incomplete
    water_map: Incomplete
    wrap: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class FluidSimulation:
    _block: Incomplete
    cell_size: Incomplete
    damping: Incomplete
    dt: Incomplete
    gravity: Incomplete
    height: Incomplete
    height_map: Incomplete
    mode: Incomplete
    steps: Incomplete
    water_map: Incomplete
    water_map_next: Incomplete
    water_map_previous: Incomplete
    wave_speed: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Noise:
    _block: Incomplete
    angle: Incomplete
    height: Incomplete
    image: Incomplete
    period: Incomplete
    period_x: Incomplete
    period_y: Incomplete
    period_z: Incomplete
    seed: Incomplete
    type: Incomplete
    warp_amp: Incomplete
    warp_scale: Incomplete
    width: Incomplete
    x: Incomplete
    y: Incomplete
    z: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class NoiseGenerator:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        Gradient2D: ClassVar[NoiseGenerator.Type] = ...
        Gradient3D: ClassVar[NoiseGenerator.Type] = ...
        Hash2D: ClassVar[NoiseGenerator.Type] = ...
        Hash3D: ClassVar[NoiseGenerator.Type] = ...
        Value2D: ClassVar[NoiseGenerator.Type] = ...
        Value3D: ClassVar[NoiseGenerator.Type] = ...
        WarpedValue2D: ClassVar[NoiseGenerator.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _hashable_values_: ClassVar[list] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _unhashable_values_map_: ClassVar[dict] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    Gradient2D: ClassVar[NoiseGenerator.Type] = ...
    Gradient3D: ClassVar[NoiseGenerator.Type] = ...
    Hash2D: ClassVar[NoiseGenerator.Type] = ...
    Hash3D: ClassVar[NoiseGenerator.Type] = ...
    Value2D: ClassVar[NoiseGenerator.Type] = ...
    Value3D: ClassVar[NoiseGenerator.Type] = ...
    WarpedValue2D: ClassVar[NoiseGenerator.Type] = ...
    angle: Incomplete
    period: Incomplete
    scale: Incomplete
    seed: Incomplete
    type: Incomplete
    warp_amp: Incomplete
    warp_scale: Incomplete
    x: Incomplete
    y: Incomplete
    z: Incomplete
    def __init__(self) -> None: ...
    def fill(self, arg) -> None: ...
    def generate(self, *args, **kwargs): ...

class PyNativeObjectTest:
    array: Incomplete
    test: Incomplete
    def __init__(self, arg) -> None: ...
    def process(self) -> None: ...

class Resample:
    _block: Incomplete
    angle: Incomplete
    function_mode: Incomplete
    input: Incomplete
    map_x: Incomplete
    map_y: Incomplete
    offset_x: Incomplete
    offset_y: Incomplete
    output: Incomplete
    relative_offset: Incomplete
    sample_mode: Incomplete
    scale_by_output_size: Incomplete
    def __init__(self) -> None: ...
    def process(self) -> None: ...

class Tectonics:
    _block: Incomplete
    height: Incomplete
    height_map: Incomplete
    test: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self, *args, **kwargs): ...

class TemplateClass3:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        APPLE: ClassVar[TemplateClass3.Type] = ...
        ORANGE: ClassVar[TemplateClass3.Type] = ...
        POTATO: ClassVar[TemplateClass3.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _hashable_values_: ClassVar[list] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _unhashable_values_map_: ClassVar[dict] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    APPLE: ClassVar[TemplateClass3.Type] = ...
    ORANGE: ClassVar[TemplateClass3.Type] = ...
    POTATO: ClassVar[TemplateClass3.Type] = ...
    _block: Incomplete
    height: Incomplete
    image: Incomplete
    test: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    def process(self, *args, **kwargs): ...
    def test_array3d(self) -> None: ...

class TemplateClass4:
    class Type(enum.Enum):
        __new__: ClassVar[Callable] = ...
        APPLE: ClassVar[TemplateClass4.Type] = ...
        ORANGE: ClassVar[TemplateClass4.Type] = ...
        POTATO: ClassVar[TemplateClass4.Type] = ...
        _generate_next_value_: ClassVar[Callable] = ...
        _hashable_values_: ClassVar[list] = ...
        _member_map_: ClassVar[dict] = ...
        _member_names_: ClassVar[list] = ...
        _member_type_: ClassVar[type[object]] = ...
        _unhashable_values_: ClassVar[list] = ...
        _unhashable_values_map_: ClassVar[dict] = ...
        _use_args_: ClassVar[bool] = ...
        _value2member_map_: ClassVar[dict] = ...
        _value_repr_: ClassVar[None] = ...
        __nb_enum__: ClassVar[PyCapsule] = ...
        @classmethod
        def _new_member_(cls, *args, **kwargs): ...
    APPLE: ClassVar[TemplateClass4.Type] = ...
    ORANGE: ClassVar[TemplateClass4.Type] = ...
    POTATO: ClassVar[TemplateClass4.Type] = ...
    _block: Incomplete
    _height: Incomplete
    _width: Incomplete
    device_array_2d_test: Incomplete
    height_map: Incomplete
    image: Incomplete
    test_bool: Incomplete
    test_float: Incomplete
    test_int: Incomplete
    def __init__(self) -> None: ...
    def process(self, *args, **kwargs): ...
