/*

numpy helper functions with new templates

these allow converting to and from the custom Array2D type and numpy arrays, also plain vectors



⚠️ generated by copilot asking it to convert my old ones to templates be careful for now!

*/
#pragma once

#include "core.h"
#include "cuda_types.cuh"

#include <cstring> // required for std::memcpy in linux (not windows)
#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <vector>

// helpers to make python objects which is a bit convoluted from python
namespace python_helper {

namespace nb = nanobind; // shortcut

#pragma region TYPE_MAPPING

// Type-to-dtype mapping
template <typename T>
struct numpy_dtype; // no default

template <>
struct numpy_dtype<float> {
    static constexpr auto value = "float32";
};
template <>
struct numpy_dtype<double> {
    static constexpr auto value = "float64";
};
template <>
struct numpy_dtype<int> {
    static constexpr auto value = "int32";
};
template <>
struct numpy_dtype<long long> {
    static constexpr auto value = "int64";
};
template <>
struct numpy_dtype<uint8_t> {
    static constexpr auto value = "uint8";
};
template <>
struct numpy_dtype<bool> {
    static constexpr auto value = "bool_";
};
// …extend as needed

#pragma endregion

#pragma region CREATE_EMPTY

// get a numpy array (2D)
template <typename T>
inline nb::ndarray<nb::numpy, T> get_numpy_array(int height, int width) {
    nb::module_ np = nb::module_::import_("numpy");
    nb::object arr_obj = np.attr("empty")(
        nb::make_tuple(height, width),
        numpy_dtype<T>::value);
    return nb::cast<nb::ndarray<nb::numpy, T>>(arr_obj);
}

// get a numpy array (3D)
template <typename T>
inline nb::ndarray<nb::numpy, T> get_numpy_array(int height, int width, int depth) {
    nb::module_ np = nb::module_::import_("numpy");
    nb::object arr_obj = np.attr("empty")(
        nb::make_tuple(height, width, depth),
        numpy_dtype<T>::value);
    return nb::cast<nb::ndarray<nb::numpy, T>>(arr_obj);
}

// inline nb::ndarray<nb::numpy, float> get_numpy_float_array(int height, int width) {
//     return get_numpy_array<float>(height, width);
// }

// inline nb::ndarray<nb::numpy, float> get_numpy_float_array(int height, int width, int depth) {
//     return get_numpy_array<float>(height, width, depth);
// }

#pragma endregion

#pragma region VECTOR

// Convert ndarray -> std::vector<T>
template <typename T>
inline std::vector<T> numpy_array_to_vector(nb::ndarray<T, nb::c_contig> arr) {
    if (arr.ndim() != 2)
        throw std::runtime_error("Input must be a 2D array");

    size_t size = arr.shape(0) * arr.shape(1);
    std::vector<T> result(size);
    std::memcpy(result.data(), arr.data(), size * sizeof(T));
    return result;
}

// Convert std::vector<T> -> ndarray<T>
template <typename T>
inline nb::ndarray<nb::numpy, T> vector_to_numpy_array(const std::vector<T> &source, int height, int width) {

    size_t size = static_cast<size_t>(height) * static_cast<size_t>(width);
    if (source.size() != size)
        throw std::runtime_error("Source vector size doesn't match requested dimensions");

    auto arr = get_numpy_array<T>(height, width); // uses the dtype traits

    std::memcpy(arr.data(), source.data(), size * sizeof(T));
    return arr;
}

#pragma endregion

#pragma region ARRAY2D

// ndarray<T> -> core::types::Array2D<T>
template <typename T>
inline core::types::Array2D<T> numpy_array_to_array2d(nb::ndarray<T, nb::c_contig> arr) {
    if (arr.ndim() != 2)
        throw std::runtime_error("Input must be a 2D array");

    size_t height = arr.shape(0);
    size_t width = arr.shape(1);

    core::types::Array2D<T> result(width, height);
    std::memcpy(result.data(), arr.data(), width * height * sizeof(T));
    return result;
}

// core::types::Array2D<T> -> ndarray<T>
template <typename T>
inline nb::ndarray<nb::numpy, T> array2d_to_numpy_array(const core::types::Array2D<T> &source) {
    size_t width = source.get_width();
    size_t height = source.get_height();
    size_t size = width * height;

    auto arr = get_numpy_array<T>(height, width); // uses dtype traits

    std::memcpy(arr.data(), source.data(), size * sizeof(T));
    return arr;
}

#pragma endregion

#pragma region ARRAY3D

// ndarray<T> -> core::types::Array3D<T>
template <typename T>
inline core::types::Array3D<T> numpy_array_to_array3d(nb::ndarray<T, nb::c_contig> arr) {
    if (arr.ndim() != 3)
        throw std::runtime_error("Input must be a 3D array");

    size_t height = arr.shape(0);
    size_t width = arr.shape(1);
    size_t depth = arr.shape(2);

    core::types::Array3D<T> result(width, height, depth);
    std::memcpy(result.data(), arr.data(), width * height * depth * sizeof(T));
    return result;
}

// core::types::Array3D<T> -> ndarray<T>
template <typename T>
inline nb::ndarray<nb::numpy, T> array3d_to_numpy_array(const core::types::Array3D<T> &source) {
    size_t width = source.get_width();
    size_t height = source.get_height();
    size_t depth = source.get_depth();
    size_t size = width * height * depth;

    auto arr = get_numpy_array<T>(height, width, depth); // overload for 3D

    std::memcpy(arr.data(), source.data(), size * sizeof(T));
    return arr;
}

#pragma endregion

#pragma region SHARED_MEMORY_NUMPY_EXPERIMENT

template <typename T>
nb::ndarray<nb::numpy, T> array3d_to_numpy_view(core::types::Array3D<T> &source) {
    return nb::ndarray<nb::numpy, T>(
        source.data(),
        {source.get_height(), source.get_width(), source.get_depth()},
        {sizeof(T) * source.get_width() * source.get_depth(),
         sizeof(T) * source.get_depth(),
         sizeof(T)});
}

#pragma endregion

#pragma region DEVICE_ARRAY_2D

// download a DeviceArray2D's data to a numpy array
template <typename T>
inline nb::ndarray<nb::numpy, T> device_array_2d_to_numpy(const core::cuda::DeviceArray2D<T> &device_array_2d) {
    auto array = python_helper::get_numpy_array<T>(device_array_2d.height(), device_array_2d.width());
    device_array_2d.download(array.data());
    return array;
}

// upload a numpy array's data to a DeviceArray2D
template <typename T>
inline void numpy_to_device_array_2d(
    const nb::ndarray<T, nb::c_contig> &array,
    core::cuda::DeviceArray2D<T> &device_array_2d) {
    if (array.ndim() != 2) {
        throw std::runtime_error("Input must be a 2D NumPy array");
    }
    device_array_2d.upload(array.data(), array.shape(1), array.shape(0)); // Upload raw pointer data into device array
}

#pragma endregion

} // namespace python_helper